#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.845612
//DO NOT EDIT THIS FILE MANUALLY!

struct CDActivities {
	int ActivityID;
	std::string Description;
	std::string ActivityName;
	std::string scoreName;
	std::string value1Name;
	std::string value2Name;
	bool scoreSort;
	bool value1Sort;
	bool value2Sort;
	int instanceMapID;
	int minTeams;
	int maxTeams;
	int minTeamSize;
	int maxTeamSize;
	int waitTime;
	int startDelay;
};

class CDActivitiesTable : public CDTable {
private:
	std::vector<CDActivities> m_entries;
public:
	CDActivitiesTable();
	~CDActivitiesTable();
	std::string GetName(void) const override;

std::vector<CDActivities> Query(std::function<bool(CDActivities)> predicate);
	std::vector<CDActivities> GetEntries(void) const;
};
