#include "CDActivityRewardsTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.848603
//DO NOT EDIT THIS FILE MANUALLY!

CDActivityRewardsTable::CDActivityRewardsTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM ActivityRewards");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM ActivityRewards");
	while (!tableData.eof()) {
		CDActivityRewards entry;
		entry.objectTemplate = tableData.getIntField(0, int{});
		entry.ActivityRewardIndex = tableData.getIntField(1, int{});
		entry.activityRating = tableData.getIntField(2, int{});
		entry.LootMatrixIndex = tableData.getIntField(3, int{});
		entry.CurrencyIndex = tableData.getIntField(4, int{});
		entry.ChallengeRating = tableData.getIntField(5, int{});
		entry.description = tableData.getStringField(6, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDActivityRewardsTable::~CDActivityRewardsTable() {
}

std::string CDActivityRewardsTable::GetName(void) const {
	return "ActivityRewards";
}

std::vector<CDActivityRewards> CDActivityRewardsTable::Query(std::function<bool(CDActivityRewards)> predicate) {
	std::vector<CDActivityRewards> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDActivityRewards> CDActivityRewardsTable::GetEntries(void) const {
	return this->m_entries;
}
