#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.851597
//DO NOT EDIT THIS FILE MANUALLY!

struct CDActivityText {
	int activityID;
	std::string type;
	std::string text;
};

class CDActivityTextTable : public CDTable {
private:
	std::vector<CDActivityText> m_entries;
public:
	CDActivityTextTable();
	~CDActivityTextTable();
	std::string GetName(void) const override;

std::vector<CDActivityText> Query(std::function<bool(CDActivityText)> predicate);
	std::vector<CDActivityText> GetEntries(void) const;
};
