#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.847606
//DO NOT EDIT THIS FILE MANUALLY!

struct CDActivityRewards {
	int objectTemplate;
	int ActivityRewardIndex;
	int activityRating;
	int LootMatrixIndex;
	int CurrencyIndex;
	int ChallengeRating;
	std::string description;
};

class CDActivityRewardsTable : public CDTable {
private:
	std::vector<CDActivityRewards> m_entries;
public:
	CDActivityRewardsTable();
	~CDActivityRewardsTable();
	std::string GetName(void) const override;

std::vector<CDActivityRewards> Query(std::function<bool(CDActivityRewards)> predicate);
	std::vector<CDActivityRewards> GetEntries(void) const;
};
