#include "CDActivityTextTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.853590
//DO NOT EDIT THIS FILE MANUALLY!

CDActivityTextTable::CDActivityTextTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM ActivityText");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM ActivityText");
	while (!tableData.eof()) {
		CDActivityText entry;
		entry.activityID = tableData.getIntField(0, int{});
		entry.type = tableData.getStringField(1, std::string{}.c_str());
		entry.text = tableData.getStringField(2, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDActivityTextTable::~CDActivityTextTable() {
}

std::string CDActivityTextTable::GetName(void) const {
	return "ActivityText";
}

std::vector<CDActivityText> CDActivityTextTable::Query(std::function<bool(CDActivityText)> predicate) {
	std::vector<CDActivityText> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDActivityText> CDActivityTextTable::GetEntries(void) const {
	return this->m_entries;
}
