#include "CDAICombatBehaviorTypesTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.856100
//DO NOT EDIT THIS FILE MANUALLY!

CDAICombatBehaviorTypesTable::CDAICombatBehaviorTypesTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM AICombatBehaviorTypes");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM AICombatBehaviorTypes");
	while (!tableData.eof()) {
		CDAICombatBehaviorTypes entry;
		entry.id = tableData.getIntField(0, int{});
		entry.name = tableData.getStringField(1, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDAICombatBehaviorTypesTable::~CDAICombatBehaviorTypesTable() {
}

std::string CDAICombatBehaviorTypesTable::GetName(void) const {
	return "AICombatBehaviorTypes";
}

std::vector<CDAICombatBehaviorTypes> CDAICombatBehaviorTypesTable::Query(std::function<bool(CDAICombatBehaviorTypes)> predicate) {
	std::vector<CDAICombatBehaviorTypes> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDAICombatBehaviorTypes> CDAICombatBehaviorTypesTable::GetEntries(void) const {
	return this->m_entries;
}
