#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.862458
//DO NOT EDIT THIS FILE MANUALLY!

struct CDAICombatRoleTypes {
	int id;
	std::string name;
};

class CDAICombatRoleTypesTable : public CDTable {
private:
	std::vector<CDAICombatRoleTypes> m_entries;
public:
	CDAICombatRoleTypesTable();
	~CDAICombatRoleTypesTable();
	std::string GetName(void) const override;

std::vector<CDAICombatRoleTypes> Query(std::function<bool(CDAICombatRoleTypes)> predicate);
	std::vector<CDAICombatRoleTypes> GetEntries(void) const;
};
