#include "CDAICombatRolesTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.859415
//DO NOT EDIT THIS FILE MANUALLY!

CDAICombatRolesTable::CDAICombatRolesTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM AICombatRoles");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM AICombatRoles");
	while (!tableData.eof()) {
		CDAICombatRoles entry;
		entry.id = tableData.getIntField(0, int{});
		entry.preferredRole = tableData.getIntField(1, int{});
		entry.description = tableData.getStringField(2, std::string{}.c_str());
		entry.specifiedMinRangeNOUSE = tableData.getFloatField(3, float{});
		entry.specifiedMaxRangeNOUSE = tableData.getFloatField(4, float{});
		entry.specificMinRange = tableData.getFloatField(5, float{});
		entry.specificMaxRange = tableData.getFloatField(6, float{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDAICombatRolesTable::~CDAICombatRolesTable() {
}

std::string CDAICombatRolesTable::GetName(void) const {
	return "AICombatRoles";
}

std::vector<CDAICombatRoles> CDAICombatRolesTable::Query(std::function<bool(CDAICombatRoles)> predicate) {
	std::vector<CDAICombatRoles> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDAICombatRoles> CDAICombatRolesTable::GetEntries(void) const {
	return this->m_entries;
}
