#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.855105
//DO NOT EDIT THIS FILE MANUALLY!

struct CDAICombatBehaviorTypes {
	int id;
	std::string name;
};

class CDAICombatBehaviorTypesTable : public CDTable {
private:
	std::vector<CDAICombatBehaviorTypes> m_entries;
public:
	CDAICombatBehaviorTypesTable();
	~CDAICombatBehaviorTypesTable();
	std::string GetName(void) const override;

std::vector<CDAICombatBehaviorTypes> Query(std::function<bool(CDAICombatBehaviorTypes)> predicate);
	std::vector<CDAICombatBehaviorTypes> GetEntries(void) const;
};
