#include "CDAICombatRoleTypesTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.862694
//DO NOT EDIT THIS FILE MANUALLY!

CDAICombatRoleTypesTable::CDAICombatRoleTypesTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM AICombatRoleTypes");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM AICombatRoleTypes");
	while (!tableData.eof()) {
		CDAICombatRoleTypes entry;
		entry.id = tableData.getIntField(0, int{});
		entry.name = tableData.getStringField(1, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDAICombatRoleTypesTable::~CDAICombatRoleTypesTable() {
}

std::string CDAICombatRoleTypesTable::GetName(void) const {
	return "AICombatRoleTypes";
}

std::vector<CDAICombatRoleTypes> CDAICombatRoleTypesTable::Query(std::function<bool(CDAICombatRoleTypes)> predicate) {
	std::vector<CDAICombatRoleTypes> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDAICombatRoleTypes> CDAICombatRoleTypesTable::GetEntries(void) const {
	return this->m_entries;
}
