#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.868915
//DO NOT EDIT THIS FILE MANUALLY!

struct CDAnimations {
	int animationGroupID;
	std::string animation_type;
	std::string animation_name;
	float chance_to_play;
	int min_loops;
	int max_loops;
	float animation_length;
	std::string sound1;
	std::string sound2;
	std::string sound3;
	std::string sound4;
	std::string sound5;
	std::string leftSound;
	std::string rightSound;
	bool hideEquip;
	bool ignoreUpperBody;
	bool restartable;
	std::string face_animation_name;
};

class CDAnimationsTable : public CDTable {
private:
	std::vector<CDAnimations> m_entries;
public:
	CDAnimationsTable();
	~CDAnimationsTable();
	std::string GetName(void) const override;

std::vector<CDAnimations> Query(std::function<bool(CDAnimations)> predicate);
	std::vector<CDAnimations> GetEntries(void) const;
};
