#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.870909
//DO NOT EDIT THIS FILE MANUALLY!

struct CDBaseCombatAIComponent {
	int id;
	int behaviorType;
	float combatRoundLength;
	int combatRole;
	float minRoundLength;
	float maxRoundLength;
	float tetherSpeed;
	float pursuitSpeed;
	float combatStartDelay;
};

class CDBaseCombatAIComponentTable : public CDTable {
private:
	std::vector<CDBaseCombatAIComponent> m_entries;
public:
	CDBaseCombatAIComponentTable();
	~CDBaseCombatAIComponentTable();
	std::string GetName(void) const override;

std::vector<CDBaseCombatAIComponent> Query(std::function<bool(CDBaseCombatAIComponent)> predicate);
	std::vector<CDBaseCombatAIComponent> GetEntries(void) const;
};
