#include "CDBehaviorParameterTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.881145
//DO NOT EDIT THIS FILE MANUALLY!

CDBehaviorParameterTable::CDBehaviorParameterTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM BehaviorParameter");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM BehaviorParameter");
	while (!tableData.eof()) {
		CDBehaviorParameter entry;
		entry.behaviorID = tableData.getIntField(0, int{});
		entry.parameterID = tableData.getStringField(1, std::string{}.c_str());
		entry.value = tableData.getFloatField(2, float{});
		entry._internalSkillID = tableData.getIntField(3, int{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDBehaviorParameterTable::~CDBehaviorParameterTable() {
}

std::string CDBehaviorParameterTable::GetName(void) const {
	return "BehaviorParameter";
}

std::vector<CDBehaviorParameter> CDBehaviorParameterTable::Query(std::function<bool(CDBehaviorParameter)> predicate) {
	std::vector<CDBehaviorParameter> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDBehaviorParameter> CDBehaviorParameterTable::GetEntries(void) const {
	return this->m_entries;
}
