#include "CDBehaviorTemplateTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.885134
//DO NOT EDIT THIS FILE MANUALLY!

CDBehaviorTemplateTable::CDBehaviorTemplateTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM BehaviorTemplate");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM BehaviorTemplate");
	while (!tableData.eof()) {
		CDBehaviorTemplate entry;
		entry.behaviorID = tableData.getIntField(0, int{});
		entry.templateID = tableData.getIntField(1, int{});
		entry.effectID = tableData.getIntField(2, int{});
		entry.effectHandle = tableData.getStringField(3, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDBehaviorTemplateTable::~CDBehaviorTemplateTable() {
}

std::string CDBehaviorTemplateTable::GetName(void) const {
	return "BehaviorTemplate";
}

std::vector<CDBehaviorTemplate> CDBehaviorTemplateTable::Query(std::function<bool(CDBehaviorTemplate)> predicate) {
	std::vector<CDBehaviorTemplate> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDBehaviorTemplate> CDBehaviorTemplateTable::GetEntries(void) const {
	return this->m_entries;
}
