#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.887128
//DO NOT EDIT THIS FILE MANUALLY!

struct CDBehaviorTemplateName {
	int templateID;
	std::string name;
};

class CDBehaviorTemplateNameTable : public CDTable {
private:
	std::vector<CDBehaviorTemplateName> m_entries;
public:
	CDBehaviorTemplateNameTable();
	~CDBehaviorTemplateNameTable();
	std::string GetName(void) const override;

std::vector<CDBehaviorTemplateName> Query(std::function<bool(CDBehaviorTemplateName)> predicate);
	std::vector<CDBehaviorTemplateName> GetEntries(void) const;
};
