#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.879169
//DO NOT EDIT THIS FILE MANUALLY!

struct CDBehaviorParameter {
	int behaviorID;
	std::string parameterID;
	float value;
	int _internalSkillID;
};

class CDBehaviorParameterTable : public CDTable {
private:
	std::vector<CDBehaviorParameter> m_entries;
public:
	CDBehaviorParameterTable();
	~CDBehaviorParameterTable();
	std::string GetName(void) const override;

std::vector<CDBehaviorParameter> Query(std::function<bool(CDBehaviorParameter)> predicate);
	std::vector<CDBehaviorParameter> GetEntries(void) const;
};
