#include "CDBehaviorTemplateNameTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.888126
//DO NOT EDIT THIS FILE MANUALLY!

CDBehaviorTemplateNameTable::CDBehaviorTemplateNameTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM BehaviorTemplateName");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM BehaviorTemplateName");
	while (!tableData.eof()) {
		CDBehaviorTemplateName entry;
		entry.templateID = tableData.getIntField(0, int{});
		entry.name = tableData.getStringField(1, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDBehaviorTemplateNameTable::~CDBehaviorTemplateNameTable() {
}

std::string CDBehaviorTemplateNameTable::GetName(void) const {
	return "BehaviorTemplateName";
}

std::vector<CDBehaviorTemplateName> CDBehaviorTemplateNameTable::Query(std::function<bool(CDBehaviorTemplateName)> predicate) {
	std::vector<CDBehaviorTemplateName> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDBehaviorTemplateName> CDBehaviorTemplateNameTable::GetEntries(void) const {
	return this->m_entries;
}
