#include "CDBrickIDTableTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.904085
//DO NOT EDIT THIS FILE MANUALLY!

CDBrickIDTableTable::CDBrickIDTableTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM BrickIDTable");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM BrickIDTable");
	while (!tableData.eof()) {
		CDBrickIDTable entry;
		entry.NDObjectID = tableData.getIntField(0, int{});
		entry.LEGOBrickID = tableData.getIntField(1, int{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDBrickIDTableTable::~CDBrickIDTableTable() {
}

std::string CDBrickIDTableTable::GetName(void) const {
	return "BrickIDTable";
}

std::vector<CDBrickIDTable> CDBrickIDTableTable::Query(std::function<bool(CDBrickIDTable)> predicate) {
	std::vector<CDBrickIDTable> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDBrickIDTable> CDBrickIDTableTable::GetEntries(void) const {
	return this->m_entries;
}
