#include "CDbrickAttributesTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.898117
//DO NOT EDIT THIS FILE MANUALLY!

CDbrickAttributesTable::CDbrickAttributesTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM brickAttributes");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM brickAttributes");
	while (!tableData.eof()) {
		CDbrickAttributes entry;
		entry.ID = tableData.getIntField(0, int{});
		entry.name = tableData.getStringField(1, std::string{}.c_str());
		entry.icon_asset = tableData.getStringField(2, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDbrickAttributesTable::~CDbrickAttributesTable() {
}

std::string CDbrickAttributesTable::GetName(void) const {
	return "brickAttributes";
}

std::vector<CDbrickAttributes> CDbrickAttributesTable::Query(std::function<bool(CDbrickAttributes)> predicate) {
	std::vector<CDbrickAttributes> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDbrickAttributes> CDbrickAttributesTable::GetEntries(void) const {
	return this->m_entries;
}
