#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.900094
//DO NOT EDIT THIS FILE MANUALLY!

struct CDBrickColors {
	int id;
	float red;
	float green;
	float blue;
	float alpha;
	int legopaletteid;
	std::string description;
	int validTypes;
	int validCharacters;
	bool factoryValid;
};

class CDBrickColorsTable : public CDTable {
private:
	std::vector<CDBrickColors> m_entries;
public:
	CDBrickColorsTable();
	~CDBrickColorsTable();
	std::string GetName(void) const override;

std::vector<CDBrickColors> Query(std::function<bool(CDBrickColors)> predicate);
	std::vector<CDBrickColors> GetEntries(void) const;
};
