#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.903102
//DO NOT EDIT THIS FILE MANUALLY!

struct CDBrickIDTable {
	int NDObjectID;
	int LEGOBrickID;
};

class CDBrickIDTableTable : public CDTable {
private:
	std::vector<CDBrickIDTable> m_entries;
public:
	CDBrickIDTableTable();
	~CDBrickIDTableTable();
	std::string GetName(void) const override;

std::vector<CDBrickIDTable> Query(std::function<bool(CDBrickIDTable)> predicate);
	std::vector<CDBrickIDTable> GetEntries(void) const;
};
