#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.896104
//DO NOT EDIT THIS FILE MANUALLY!

struct CDbrickAttributes {
	int ID;
	std::string name;
	std::string icon_asset;
};

class CDbrickAttributesTable : public CDTable {
private:
	std::vector<CDbrickAttributes> m_entries;
public:
	CDbrickAttributesTable();
	~CDbrickAttributesTable();
	std::string GetName(void) const override;

std::vector<CDbrickAttributes> Query(std::function<bool(CDbrickAttributes)> predicate);
	std::vector<CDbrickAttributes> GetEntries(void) const;
};
