#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.912062
//DO NOT EDIT THIS FILE MANUALLY!

struct CDChoiceBuildComponent {
	int id;
	std::string selections;
	int imaginationOverride;
};

class CDChoiceBuildComponentTable : public CDTable {
private:
	std::vector<CDChoiceBuildComponent> m_entries;
public:
	CDChoiceBuildComponentTable();
	~CDChoiceBuildComponentTable();
	std::string GetName(void) const override;

std::vector<CDChoiceBuildComponent> Query(std::function<bool(CDChoiceBuildComponent)> predicate);
	std::vector<CDChoiceBuildComponent> GetEntries(void) const;
};
