#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.922038
//DO NOT EDIT THIS FILE MANUALLY!

struct CDComponentsRegistry {
	int id;
	int component_type;
	int component_id;
};

class CDComponentsRegistryTable : public CDTable {
private:
	std::vector<CDComponentsRegistry> m_entries;
public:
	CDComponentsRegistryTable();
	~CDComponentsRegistryTable();
	std::string GetName(void) const override;

std::vector<CDComponentsRegistry> Query(std::function<bool(CDComponentsRegistry)> predicate);
	std::vector<CDComponentsRegistry> GetEntries(void) const;
};
