#include "CDComponentsRegistryTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.923033
//DO NOT EDIT THIS FILE MANUALLY!

CDComponentsRegistryTable::CDComponentsRegistryTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM ComponentsRegistry");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM ComponentsRegistry");
	while (!tableData.eof()) {
		CDComponentsRegistry entry;
		entry.id = tableData.getIntField(0, int{});
		entry.component_type = tableData.getIntField(1, int{});
		entry.component_id = tableData.getIntField(2, int{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDComponentsRegistryTable::~CDComponentsRegistryTable() {
}

std::string CDComponentsRegistryTable::GetName(void) const {
	return "ComponentsRegistry";
}

std::vector<CDComponentsRegistry> CDComponentsRegistryTable::Query(std::function<bool(CDComponentsRegistry)> predicate) {
	std::vector<CDComponentsRegistry> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDComponentsRegistry> CDComponentsRegistryTable::GetEntries(void) const {
	return this->m_entries;
}
