#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.917049
//DO NOT EDIT THIS FILE MANUALLY!

struct CDCollectibleComponent {
	int id;
	int requirement_mission;
};

class CDCollectibleComponentTable : public CDTable {
private:
	std::vector<CDCollectibleComponent> m_entries;
public:
	CDCollectibleComponentTable();
	~CDCollectibleComponentTable();
	std::string GetName(void) const override;

std::vector<CDCollectibleComponent> Query(std::function<bool(CDCollectibleComponent)> predicate);
	std::vector<CDCollectibleComponent> GetEntries(void) const;
};
