#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.925028
//DO NOT EDIT THIS FILE MANUALLY!

struct CDControlSchemes {
	int control_scheme;
	std::string scheme_name;
	float rotation_speed;
	float walk_forward_speed;
	float walk_backward_speed;
	float walk_strafe_speed;
	float walk_strafe_forward_speed;
	float walk_strafe_backward_speed;
	float run_backward_speed;
	float run_strafe_speed;
	float run_strafe_forward_speed;
	float run_strafe_backward_speed;
	float keyboard_zoom_sensitivity;
	float keyboard_pitch_sensitivity;
	float keyboard_yaw_sensitivity;
	float mouse_zoom_wheel_sensitivity;
	float x_mouse_move_sensitivity_modifier;
	float y_mouse_move_sensitivity_modifier;
	float freecam_speed_modifier;
	float freecam_slow_speed_multiplier;
	float freecam_fast_speed_multiplier;
	float freecam_mouse_modifier;
	float gamepad_pitch_rot_sensitivity;
	float gamepad_yaw_rot_sensitivity;
	float gamepad_trigger_sensitivity;
};

class CDControlSchemesTable : public CDTable {
private:
	std::vector<CDControlSchemes> m_entries;
public:
	CDControlSchemesTable();
	~CDControlSchemesTable();
	std::string GetName(void) const override;

std::vector<CDControlSchemes> Query(std::function<bool(CDControlSchemes)> predicate);
	std::vector<CDControlSchemes> GetEntries(void) const;
};
