#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.933006
//DO NOT EDIT THIS FILE MANUALLY!

struct CDCurrencyDenominations {
	int value;
	int objectid;
};

class CDCurrencyDenominationsTable : public CDTable {
private:
	std::vector<CDCurrencyDenominations> m_entries;
public:
	CDCurrencyDenominationsTable();
	~CDCurrencyDenominationsTable();
	std::string GetName(void) const override;

std::vector<CDCurrencyDenominations> Query(std::function<bool(CDCurrencyDenominations)> predicate);
	std::vector<CDCurrencyDenominations> GetEntries(void) const;
};
