#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.935999
//DO NOT EDIT THIS FILE MANUALLY!

struct CDCurrencyIndex {
	int CurrencyIndex;
	std::string description;
};

class CDCurrencyIndexTable : public CDTable {
private:
	std::vector<CDCurrencyIndex> m_entries;
public:
	CDCurrencyIndexTable();
	~CDCurrencyIndexTable();
	std::string GetName(void) const override;

std::vector<CDCurrencyIndex> Query(std::function<bool(CDCurrencyIndex)> predicate);
	std::vector<CDCurrencyIndex> GetEntries(void) const;
};
