#include "CDCurrencyIndexTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.936996
//DO NOT EDIT THIS FILE MANUALLY!

CDCurrencyIndexTable::CDCurrencyIndexTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM CurrencyIndex");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM CurrencyIndex");
	while (!tableData.eof()) {
		CDCurrencyIndex entry;
		entry.CurrencyIndex = tableData.getIntField(0, int{});
		entry.description = tableData.getStringField(1, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDCurrencyIndexTable::~CDCurrencyIndexTable() {
}

std::string CDCurrencyIndexTable::GetName(void) const {
	return "CurrencyIndex";
}

std::vector<CDCurrencyIndex> CDCurrencyIndexTable::Query(std::function<bool(CDCurrencyIndex)> predicate) {
	std::vector<CDCurrencyIndex> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDCurrencyIndex> CDCurrencyIndexTable::GetEntries(void) const {
	return this->m_entries;
}
