#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.941997
//DO NOT EDIT THIS FILE MANUALLY!

struct CDCurrencyTable {
	int currencyIndex;
	int npcminlevel;
	int minvalue;
	int maxvalue;
	int id;
};

class CDCurrencyTableTable : public CDTable {
private:
	std::vector<CDCurrencyTable> m_entries;
public:
	CDCurrencyTableTable();
	~CDCurrencyTableTable();
	std::string GetName(void) const override;

std::vector<CDCurrencyTable> Query(std::function<bool(CDCurrencyTable)> predicate);
	std::vector<CDCurrencyTable> GetEntries(void) const;
};
