#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.954948
//DO NOT EDIT THIS FILE MANUALLY!

struct CDDestructibleComponent {
	int id;
	int faction;
	int life;
	int imagination;
	int LootMatrixIndex;
	int CurrencyIndex;
	int level;
	float armor;
	int death_behavior;
	float protection_disruption;
	float protection_elemental;
	float protection_physical;
	bool isnpc;
	int attack_priority;
	bool isSmashable;
};

class CDDestructibleComponentTable : public CDTable {
private:
	std::vector<CDDestructibleComponent> m_entries;
public:
	CDDestructibleComponentTable();
	~CDDestructibleComponentTable();
	std::string GetName(void) const override;

std::vector<CDDestructibleComponent> Query(std::function<bool(CDDestructibleComponent)> predicate);
	std::vector<CDDestructibleComponent> GetEntries(void) const;
};
