#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.964921
//DO NOT EDIT THIS FILE MANUALLY!

struct CDdtproperties {
	int id;
	int objectid;
	std::string property;
	std::string value;
	std::string uvalue;
	//image lvalue;
	int version;
};

class CDdtpropertiesTable : public CDTable {
private:
	std::vector<CDdtproperties> m_entries;
public:
	CDdtpropertiesTable();
	~CDdtpropertiesTable();
	std::string GetName(void) const override;

std::vector<CDdtproperties> Query(std::function<bool(CDdtproperties)> predicate);
	std::vector<CDdtproperties> GetEntries(void) const;
};
