#include "CDEmotesTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.969908
//DO NOT EDIT THIS FILE MANUALLY!

CDEmotesTable::CDEmotesTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM Emotes");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM Emotes");
	while (!tableData.eof()) {
		CDEmotes entry;
		entry.id = tableData.getIntField(0, int{});
		entry.outputText = tableData.getStringField(1, std::string{}.c_str());
		entry.targetText = tableData.getStringField(2, std::string{}.c_str());
		entry.animationName = tableData.getStringField(3, std::string{}.c_str());
		entry.iconFilename = tableData.getStringField(4, std::string{}.c_str());
		entry.channel = tableData.getStringField(5, std::string{}.c_str());
		entry.command = tableData.getStringField(6, std::string{}.c_str());
		entry.locked = tableData.getIntField(7, bool{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDEmotesTable::~CDEmotesTable() {
}

std::string CDEmotesTable::GetName(void) const {
	return "Emotes";
}

std::vector<CDEmotes> CDEmotesTable::Query(std::function<bool(CDEmotes)> predicate) {
	std::vector<CDEmotes> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDEmotes> CDEmotesTable::GetEntries(void) const {
	return this->m_entries;
}
