#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.968910
//DO NOT EDIT THIS FILE MANUALLY!

struct CDEmotes {
	int id;
	std::string outputText;
	std::string targetText;
	std::string animationName;
	std::string iconFilename;
	std::string channel;
	std::string command;
	bool locked;
};

class CDEmotesTable : public CDTable {
private:
	std::vector<CDEmotes> m_entries;
public:
	CDEmotesTable();
	~CDEmotesTable();
	std::string GetName(void) const override;

std::vector<CDEmotes> Query(std::function<bool(CDEmotes)> predicate);
	std::vector<CDEmotes> GetEntries(void) const;
};
