#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.972899
//DO NOT EDIT THIS FILE MANUALLY!

struct CDExhibitComponent {
	int id;
	float length;
	float width;
	float height;
	float offsetX;
	float offsetY;
	float offsetZ;
	float fReputationSizeMultiplier;
	float fImaginationCost;
};

class CDExhibitComponentTable : public CDTable {
private:
	std::vector<CDExhibitComponent> m_entries;
public:
	CDExhibitComponentTable();
	~CDExhibitComponentTable();
	std::string GetName(void) const override;

std::vector<CDExhibitComponent> Query(std::function<bool(CDExhibitComponent)> predicate);
	std::vector<CDExhibitComponent> GetEntries(void) const;
};
