#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.977888
//DO NOT EDIT THIS FILE MANUALLY!

struct CDFactions {
	int faction;
	std::string factionList;
	bool factionListFriendly;
	std::string description;
};

class CDFactionsTable : public CDTable {
private:
	std::vector<CDFactions> m_entries;
public:
	CDFactionsTable();
	~CDFactionsTable();
	std::string GetName(void) const override;

std::vector<CDFactions> Query(std::function<bool(CDFactions)> predicate);
	std::vector<CDFactions> GetEntries(void) const;
};
