#include "CDFactionsTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.979881
//DO NOT EDIT THIS FILE MANUALLY!

CDFactionsTable::CDFactionsTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM Factions");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM Factions");
	while (!tableData.eof()) {
		CDFactions entry;
		entry.faction = tableData.getIntField(0, int{});
		entry.factionList = tableData.getStringField(1, std::string{}.c_str());
		entry.factionListFriendly = tableData.getIntField(2, bool{});
		entry.description = tableData.getStringField(3, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDFactionsTable::~CDFactionsTable() {
}

std::string CDFactionsTable::GetName(void) const {
	return "Factions";
}

std::vector<CDFactions> CDFactionsTable::Query(std::function<bool(CDFactions)> predicate) {
	std::vector<CDFactions> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDFactions> CDFactionsTable::GetEntries(void) const {
	return this->m_entries;
}
