#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.982873
//DO NOT EDIT THIS FILE MANUALLY!

struct CDFlairTable {
	int id;
	std::string asset;
};

class CDFlairTableTable : public CDTable {
private:
	std::vector<CDFlairTable> m_entries;
public:
	CDFlairTableTable();
	~CDFlairTableTable();
	std::string GetName(void) const override;

std::vector<CDFlairTable> Query(std::function<bool(CDFlairTable)> predicate);
	std::vector<CDFlairTable> GetEntries(void) const;
};
