#include "CDInventoryComponentTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.994844
//DO NOT EDIT THIS FILE MANUALLY!

CDInventoryComponentTable::CDInventoryComponentTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM InventoryComponent");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM InventoryComponent");
	while (!tableData.eof()) {
		CDInventoryComponent entry;
		entry.id = tableData.getIntField(0, int{});
		entry.itemid = tableData.getIntField(1, int{});
		entry.count = tableData.getIntField(2, int{});
		entry.equip = tableData.getIntField(3, bool{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDInventoryComponentTable::~CDInventoryComponentTable() {
}

std::string CDInventoryComponentTable::GetName(void) const {
	return "InventoryComponent";
}

std::vector<CDInventoryComponent> CDInventoryComponentTable::Query(std::function<bool(CDInventoryComponent)> predicate) {
	std::vector<CDInventoryComponent> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDInventoryComponent> CDInventoryComponentTable::GetEntries(void) const {
	return this->m_entries;
}
