#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.993843
//DO NOT EDIT THIS FILE MANUALLY!

struct CDInventoryComponent {
	unsigned int id;
	int itemid;
	unsigned int count;
	bool equip;
};

class CDInventoryComponentTable : public CDTable {
private:
	std::vector<CDInventoryComponent> m_entries;
public:
	CDInventoryComponentTable();
	~CDInventoryComponentTable();
	std::string GetName(void) const override;

std::vector<CDInventoryComponent> Query(std::function<bool(CDInventoryComponent)> predicate);
	std::vector<CDInventoryComponent> GetEntries(void) const;
};
