#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.006810
//DO NOT EDIT THIS FILE MANUALLY!

struct CDItemFoodData {
	int id;
	int element_1;
	int element_1_amount;
	int element_2;
	int element_2_amount;
	int element_3;
	int element_3_amount;
	int element_4;
	int element_4_amount;
};

class CDItemFoodDataTable : public CDTable {
private:
	std::vector<CDItemFoodData> m_entries;
public:
	CDItemFoodDataTable();
	~CDItemFoodDataTable();
	std::string GetName(void) const override;

std::vector<CDItemFoodData> Query(std::function<bool(CDItemFoodData)> predicate);
	std::vector<CDItemFoodData> GetEntries(void) const;
};
