#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.009803
//DO NOT EDIT THIS FILE MANUALLY!

struct CDItemSets {
	int setID;
	std::string itemIDs;
	std::string displayName;
	std::string description;
	int skillWith2;
	int castType2;
	int skillWith3;
	int castType3;
	int skillWith4;
	int castType4;
	int skillWith5;
	int castType5;
	int skillSetWith2;
	int skillSetWith3;
	int skillSetWith4;
	int skillSetWith5;
	int skillSetWith6;
};

class CDItemSetsTable : public CDTable {
private:
	std::vector<CDItemSets> m_entries;
public:
	CDItemSetsTable();
	~CDItemSetsTable();
	std::string GetName(void) const override;

std::vector<CDItemSets> Query(std::function<bool(CDItemSets)> predicate);
	std::vector<CDItemSets> GetEntries(void) const;
};
