#include "CDItemEggDataTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.004814
//DO NOT EDIT THIS FILE MANUALLY!

CDItemEggDataTable::CDItemEggDataTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM ItemEggData");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM ItemEggData");
	while (!tableData.eof()) {
		CDItemEggData entry;
		entry.id = tableData.getIntField(0, int{});
		entry.chassie_type_id = tableData.getIntField(1, int{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDItemEggDataTable::~CDItemEggDataTable() {
}

std::string CDItemEggDataTable::GetName(void) const {
	return "ItemEggData";
}

std::vector<CDItemEggData> CDItemEggDataTable::Query(std::function<bool(CDItemEggData)> predicate) {
	std::vector<CDItemEggData> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDItemEggData> CDItemEggDataTable::GetEntries(void) const {
	return this->m_entries;
}
