#include "CDItemFoodDataTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.006810
//DO NOT EDIT THIS FILE MANUALLY!

CDItemFoodDataTable::CDItemFoodDataTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM ItemFoodData");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM ItemFoodData");
	while (!tableData.eof()) {
		CDItemFoodData entry;
		entry.id = tableData.getIntField(0, int{});
		entry.element_1 = tableData.getIntField(1, int{});
		entry.element_1_amount = tableData.getIntField(2, int{});
		entry.element_2 = tableData.getIntField(3, int{});
		entry.element_2_amount = tableData.getIntField(4, int{});
		entry.element_3 = tableData.getIntField(5, int{});
		entry.element_3_amount = tableData.getIntField(6, int{});
		entry.element_4 = tableData.getIntField(7, int{});
		entry.element_4_amount = tableData.getIntField(8, int{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDItemFoodDataTable::~CDItemFoodDataTable() {
}

std::string CDItemFoodDataTable::GetName(void) const {
	return "ItemFoodData";
}

std::vector<CDItemFoodData> CDItemFoodDataTable::Query(std::function<bool(CDItemFoodData)> predicate) {
	std::vector<CDItemFoodData> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDItemFoodData> CDItemFoodDataTable::GetEntries(void) const {
	return this->m_entries;
}
