#include "CDItemSetSkillsTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.063657
//DO NOT EDIT THIS FILE MANUALLY!

CDItemSetSkillsTable::CDItemSetSkillsTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM ItemSetSkills");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM ItemSetSkills");
	while (!tableData.eof()) {
		CDItemSetSkills entry;
		entry.SkillSetID = tableData.getIntField(0, int{});
		entry.SkillID = tableData.getIntField(1, int{});
		entry.SkillCastType = tableData.getIntField(2, int{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDItemSetSkillsTable::~CDItemSetSkillsTable() {
}

std::string CDItemSetSkillsTable::GetName(void) const {
	return "ItemSetSkills";
}

std::vector<CDItemSetSkills> CDItemSetSkillsTable::Query(std::function<bool(CDItemSetSkills)> predicate) {
	std::vector<CDItemSetSkills> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDItemSetSkills> CDItemSetSkillsTable::GetEntries(void) const {
	return this->m_entries;
}
