#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.003604
//DO NOT EDIT THIS FILE MANUALLY!

struct CDItemEggData {
	int id;
	int chassie_type_id;
};

class CDItemEggDataTable : public CDTable {
private:
	std::vector<CDItemEggData> m_entries;
public:
	CDItemEggDataTable();
	~CDItemEggDataTable();
	std::string GetName(void) const override;

std::vector<CDItemEggData> Query(std::function<bool(CDItemEggData)> predicate);
	std::vector<CDItemEggData> GetEntries(void) const;
};
