#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:32.998113
//DO NOT EDIT THIS FILE MANUALLY!

struct CDItemComponent {
	int id;
	std::string equipLocation;
	int baseValue;
	bool isKitPiece;
	int rarity;
	int itemType;
	int itemInfo;
	bool inLootTable;
	bool inVendor;
	bool isUnique;
	bool isBOP;
	bool isBOE;
	int reqFactionID;
	int reqSpecialtyID;
	int reqSpecRank;
	int reqAchievementID;
	int stackSize;
	int color1;
	int decal;
	int offsetGroupID;
	int buildTypes;
	std::string reqPrecondition;
	int weaponType;
	int equipEffects;
	bool readyForQA;
	int itemRating;
	bool isTwoHanded;
	int minNumRequired;
	int delResIndex;
	int currencyLOT;
	int altCurrencyCost;
};

class CDItemComponentTable : public CDTable {
private:
	std::vector<CDItemComponent> m_entries;
public:
	CDItemComponentTable();
	~CDItemComponentTable();
	std::string GetName(void) const override;

std::vector<CDItemComponent> Query(std::function<bool(CDItemComponent)> predicate);
	std::vector<CDItemComponent> GetEntries(void) const;
};
