#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.050691
//DO NOT EDIT THIS FILE MANUALLY!

struct CDItemSetSkills {
	int SkillSetID;
	int SkillID;
	int SkillCastType;
};

class CDItemSetSkillsTable : public CDTable {
private:
	std::vector<CDItemSetSkills> m_entries;
public:
	CDItemSetSkillsTable();
	~CDItemSetSkillsTable();
	std::string GetName(void) const override;

std::vector<CDItemSetSkills> Query(std::function<bool(CDItemSetSkills)> predicate);
	std::vector<CDItemSetSkills> GetEntries(void) const;
};
