#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.098563
//DO NOT EDIT THIS FILE MANUALLY!

struct CDLanguageType {
	int LanguageID;
	std::string LanguageDescription;
};

class CDLanguageTypeTable : public CDTable {
private:
	std::vector<CDLanguageType> m_entries;
public:
	CDLanguageTypeTable();
	~CDLanguageTypeTable();
	std::string GetName(void) const override;

std::vector<CDLanguageType> Query(std::function<bool(CDLanguageType)> predicate);
	std::vector<CDLanguageType> GetEntries(void) const;
};
