#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.126067
//DO NOT EDIT THIS FILE MANUALLY!

struct CDLootTableIndex {
	int LootTableIndex;
	std::string description;
};

class CDLootTableIndexTable : public CDTable {
private:
	std::vector<CDLootTableIndex> m_entries;
public:
	CDLootTableIndexTable();
	~CDLootTableIndexTable();
	std::string GetName(void) const override;

std::vector<CDLootTableIndex> Query(std::function<bool(CDLootTableIndex)> predicate);
	std::vector<CDLootTableIndex> GetEntries(void) const;
};
