#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.107539
//DO NOT EDIT THIS FILE MANUALLY!

struct CDLootMatrix {
	int LootMatrixIndex;
	int LootTableIndex;
	int RarityTableIndex;
	float percent;
	int minToDrop;
	int maxToDrop;
	int id;
};

class CDLootMatrixTable : public CDTable {
private:
	std::vector<CDLootMatrix> m_entries;
public:
	CDLootMatrixTable();
	~CDLootMatrixTable();
	std::string GetName(void) const override;

std::vector<CDLootMatrix> Query(std::function<bool(CDLootMatrix)> predicate);
	std::vector<CDLootMatrix> GetEntries(void) const;
};
