#include "CDLootMatrixIndexTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.116515
//DO NOT EDIT THIS FILE MANUALLY!

CDLootMatrixIndexTable::CDLootMatrixIndexTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM LootMatrixIndex");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM LootMatrixIndex");
	while (!tableData.eof()) {
		CDLootMatrixIndex entry;
		entry.LootMatrixIndex = tableData.getIntField(0, int{});
		entry.description = tableData.getStringField(1, std::string{}.c_str());
		entry.inNpcEditor = tableData.getIntField(2, bool{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDLootMatrixIndexTable::~CDLootMatrixIndexTable() {
}

std::string CDLootMatrixIndexTable::GetName(void) const {
	return "LootMatrixIndex";
}

std::vector<CDLootMatrixIndex> CDLootMatrixIndexTable::Query(std::function<bool(CDLootMatrixIndex)> predicate) {
	std::vector<CDLootMatrixIndex> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDLootMatrixIndex> CDLootMatrixIndexTable::GetEntries(void) const {
	return this->m_entries;
}
