#include "CDLootTableIndexTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.128534
//DO NOT EDIT THIS FILE MANUALLY!

CDLootTableIndexTable::CDLootTableIndexTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM LootTableIndex");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM LootTableIndex");
	while (!tableData.eof()) {
		CDLootTableIndex entry;
		entry.LootTableIndex = tableData.getIntField(0, int{});
		entry.description = tableData.getStringField(1, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDLootTableIndexTable::~CDLootTableIndexTable() {
}

std::string CDLootTableIndexTable::GetName(void) const {
	return "LootTableIndex";
}

std::vector<CDLootTableIndex> CDLootTableIndexTable::Query(std::function<bool(CDLootTableIndex)> predicate) {
	std::vector<CDLootTableIndex> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDLootTableIndex> CDLootTableIndexTable::GetEntries(void) const {
	return this->m_entries;
}
