#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.121834
//DO NOT EDIT THIS FILE MANUALLY!

struct CDLootTable {
	int itemid;
	int LootTableIndex;
	int id;
	bool MissionDrop;
};

class CDLootTableTable : public CDTable {
private:
	std::vector<CDLootTable> m_entries;
public:
	CDLootTableTable();
	~CDLootTableTable();
	std::string GetName(void) const override;

std::vector<CDLootTable> Query(std::function<bool(CDLootTable)> predicate);
	std::vector<CDLootTable> GetEntries(void) const;
};
