#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.115518
//DO NOT EDIT THIS FILE MANUALLY!

struct CDLootMatrixIndex {
	int LootMatrixIndex;
	std::string description;
	bool inNpcEditor;
};

class CDLootMatrixIndexTable : public CDTable {
private:
	std::vector<CDLootMatrixIndex> m_entries;
public:
	CDLootMatrixIndexTable();
	~CDLootMatrixIndexTable();
	std::string GetName(void) const override;

std::vector<CDLootMatrixIndex> Query(std::function<bool(CDLootMatrixIndex)> predicate);
	std::vector<CDLootMatrixIndex> GetEntries(void) const;
};
