#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.139455
//DO NOT EDIT THIS FILE MANUALLY!

struct CDmapAssetType {
	int id;
	std::string label;
	std::string pathdir;
	std::string typelabel;
};

class CDmapAssetTypeTable : public CDTable {
private:
	std::vector<CDmapAssetType> m_entries;
public:
	CDmapAssetTypeTable();
	~CDmapAssetTypeTable();
	std::string GetName(void) const override;

std::vector<CDmapAssetType> Query(std::function<bool(CDmapAssetType)> predicate);
	std::vector<CDmapAssetType> GetEntries(void) const;
};
