#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.149428
//DO NOT EDIT THIS FILE MANUALLY!

struct CDmapComponentType {
	int id;
	std::string label;
	std::string table;
};

class CDmapComponentTypeTable : public CDTable {
private:
	std::vector<CDmapComponentType> m_entries;
public:
	CDmapComponentTypeTable();
	~CDmapComponentTypeTable();
	std::string GetName(void) const override;

std::vector<CDmapComponentType> Query(std::function<bool(CDmapComponentType)> predicate);
	std::vector<CDmapComponentType> GetEntries(void) const;
};
