#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.162393
//DO NOT EDIT THIS FILE MANUALLY!

struct CDmapItemTypes {
	int id;
	std::string description;
	std::string equipLocation;
};

class CDmapItemTypesTable : public CDTable {
private:
	std::vector<CDmapItemTypes> m_entries;
public:
	CDmapItemTypesTable();
	~CDmapItemTypesTable();
	std::string GetName(void) const override;

std::vector<CDmapItemTypes> Query(std::function<bool(CDmapItemTypes)> predicate);
	std::vector<CDmapItemTypes> GetEntries(void) const;
};
