#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.174362
//DO NOT EDIT THIS FILE MANUALLY!

struct CDmapShaders {
	int id;
	std::string label;
	int gameValue;
	int priority;
};

class CDmapShadersTable : public CDTable {
private:
	std::vector<CDmapShaders> m_entries;
public:
	CDmapShadersTable();
	~CDmapShadersTable();
	std::string GetName(void) const override;

std::vector<CDmapShaders> Query(std::function<bool(CDmapShaders)> predicate);
	std::vector<CDmapShaders> GetEntries(void) const;
};
