#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.167380
//DO NOT EDIT THIS FILE MANUALLY!

struct CDmapRenderEffects {
	int id;
	int gameID;
	std::string description;
};

class CDmapRenderEffectsTable : public CDTable {
private:
	std::vector<CDmapRenderEffects> m_entries;
public:
	CDmapRenderEffectsTable();
	~CDmapRenderEffectsTable();
	std::string GetName(void) const override;

std::vector<CDmapRenderEffects> Query(std::function<bool(CDmapRenderEffects)> predicate);
	std::vector<CDmapRenderEffects> GetEntries(void) const;
};
