#include "CDmapIconTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.157738
//DO NOT EDIT THIS FILE MANUALLY!

CDmapIconTable::CDmapIconTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM mapIcon");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM mapIcon");
	while (!tableData.eof()) {
		CDmapIcon entry;
		entry.LOT = tableData.getIntField(0, int{});
		entry.iconID = tableData.getIntField(1, int{});
		entry.iconState = tableData.getIntField(2, int{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDmapIconTable::~CDmapIconTable() {
}

std::string CDmapIconTable::GetName(void) const {
	return "mapIcon";
}

std::vector<CDmapIcon> CDmapIconTable::Query(std::function<bool(CDmapIcon)> predicate) {
	std::vector<CDmapIcon> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDmapIcon> CDmapIconTable::GetEntries(void) const {
	return this->m_entries;
}
