#include "CDmapRenderEffectsTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.169829
//DO NOT EDIT THIS FILE MANUALLY!

CDmapRenderEffectsTable::CDmapRenderEffectsTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM mapRenderEffects");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM mapRenderEffects");
	while (!tableData.eof()) {
		CDmapRenderEffects entry;
		entry.id = tableData.getIntField(0, int{});
		entry.gameID = tableData.getIntField(1, int{});
		entry.description = tableData.getStringField(2, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDmapRenderEffectsTable::~CDmapRenderEffectsTable() {
}

std::string CDmapRenderEffectsTable::GetName(void) const {
	return "mapRenderEffects";
}

std::vector<CDmapRenderEffects> CDmapRenderEffectsTable::Query(std::function<bool(CDmapRenderEffects)> predicate) {
	std::vector<CDmapRenderEffects> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDmapRenderEffects> CDmapRenderEffectsTable::GetEntries(void) const {
	return this->m_entries;
}
