#include "CDmapTextureResourceTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.182341
//DO NOT EDIT THIS FILE MANUALLY!

CDmapTextureResourceTable::CDmapTextureResourceTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM mapTextureResource");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM mapTextureResource");
	while (!tableData.eof()) {
		CDmapTextureResource entry;
		entry.id = tableData.getIntField(0, int{});
		entry.texturepath = tableData.getStringField(1, std::string{}.c_str());
		entry.soundtype = tableData.getStringField(2, std::string{}.c_str());
		entry.SurfaceType = tableData.getIntField(3, int{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDmapTextureResourceTable::~CDmapTextureResourceTable() {
}

std::string CDmapTextureResourceTable::GetName(void) const {
	return "mapTextureResource";
}

std::vector<CDmapTextureResource> CDmapTextureResourceTable::Query(std::function<bool(CDmapTextureResource)> predicate) {
	std::vector<CDmapTextureResource> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDmapTextureResource> CDmapTextureResourceTable::GetEntries(void) const {
	return this->m_entries;
}
