#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.181344
//DO NOT EDIT THIS FILE MANUALLY!

struct CDmapTextureResource {
	int id;
	std::string texturepath;
	std::string soundtype;
	int SurfaceType;
};

class CDmapTextureResourceTable : public CDTable {
private:
	std::vector<CDmapTextureResource> m_entries;
public:
	CDmapTextureResourceTable();
	~CDmapTextureResourceTable();
	std::string GetName(void) const override;

std::vector<CDmapTextureResource> Query(std::function<bool(CDmapTextureResource)> predicate);
	std::vector<CDmapTextureResource> GetEntries(void) const;
};
