#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.155412
//DO NOT EDIT THIS FILE MANUALLY!

struct CDmapIcon {
	int LOT;
	int iconID;
	int iconState;
};

class CDmapIconTable : public CDTable {
private:
	std::vector<CDmapIcon> m_entries;
public:
	CDmapIconTable();
	~CDmapIconTable();
	std::string GetName(void) const override;

std::vector<CDmapIcon> Query(std::function<bool(CDmapIcon)> predicate);
	std::vector<CDmapIcon> GetEntries(void) const;
};
