#include "CDMinifigDecals_TorsosTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.206276
//DO NOT EDIT THIS FILE MANUALLY!

CDMinifigDecals_TorsosTable::CDMinifigDecals_TorsosTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM MinifigDecals_Torsos");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM MinifigDecals_Torsos");
	while (!tableData.eof()) {
		CDMinifigDecals_Torsos entry;
		entry.ID = tableData.getIntField(0, int{});
		entry.High_path = tableData.getStringField(1, std::string{}.c_str());
		entry.CharacterCreateValid = tableData.getIntField(2, bool{});
		entry._description = tableData.getStringField(3, std::string{}.c_str());
		entry.male = tableData.getIntField(4, bool{});
		entry.female = tableData.getIntField(5, bool{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDMinifigDecals_TorsosTable::~CDMinifigDecals_TorsosTable() {
}

std::string CDMinifigDecals_TorsosTable::GetName(void) const {
	return "MinifigDecals_Torsos";
}

std::vector<CDMinifigDecals_Torsos> CDMinifigDecals_TorsosTable::Query(std::function<bool(CDMinifigDecals_Torsos)> predicate) {
	std::vector<CDMinifigDecals_Torsos> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDMinifigDecals_Torsos> CDMinifigDecals_TorsosTable::GetEntries(void) const {
	return this->m_entries;
}
