#include "CDMinifigDecals_MouthsTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.202287
//DO NOT EDIT THIS FILE MANUALLY!

CDMinifigDecals_MouthsTable::CDMinifigDecals_MouthsTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM MinifigDecals_Mouths");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM MinifigDecals_Mouths");
	while (!tableData.eof()) {
		CDMinifigDecals_Mouths entry;
		entry.ID = tableData.getIntField(0, int{});
		entry.High_path = tableData.getStringField(1, std::string{}.c_str());
		entry.Low_path = tableData.getStringField(2, std::string{}.c_str());
		entry.CharacterCreateValid = tableData.getIntField(3, bool{});
		entry.male = tableData.getIntField(4, bool{});
		entry.female = tableData.getIntField(5, bool{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDMinifigDecals_MouthsTable::~CDMinifigDecals_MouthsTable() {
}

std::string CDMinifigDecals_MouthsTable::GetName(void) const {
	return "MinifigDecals_Mouths";
}

std::vector<CDMinifigDecals_Mouths> CDMinifigDecals_MouthsTable::Query(std::function<bool(CDMinifigDecals_Mouths)> predicate) {
	std::vector<CDMinifigDecals_Mouths> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDMinifigDecals_Mouths> CDMinifigDecals_MouthsTable::GetEntries(void) const {
	return this->m_entries;
}
