#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.215253
//DO NOT EDIT THIS FILE MANUALLY!

struct CDMissionTasks {
	int id;
	int taskType;
	int target;
	std::string targetGroup;
	int targetValue;
	std::string taskParam1;
	std::string description;
	std::string largeTaskIcon;
	int IconID;
	int uid;
	int largeTaskIconID;
};

class CDMissionTasksTable : public CDTable {
private:
	std::vector<CDMissionTasks> m_entries;
public:
	CDMissionTasksTable();
	~CDMissionTasksTable();
	std::string GetName(void) const override;

std::vector<CDMissionTasks> Query(std::function<bool(CDMissionTasks)> predicate);
	std::vector<CDMissionTasks> GetEntries(void) const;
};
