#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.185562
//DO NOT EDIT THIS FILE MANUALLY!

struct CDMinifigComponent {
	int id;
	int head;
	int chest;
	int legs;
	int hairstyle;
	int haircolor;
	int chestdecal;
	int headcolor;
	int lefthand;
	int righthand;
	int eyebrowstyle;
	int eyesstyle;
	int mouthstyle;
};

class CDMinifigComponentTable : public CDTable {
private:
	std::vector<CDMinifigComponent> m_entries;
public:
	CDMinifigComponentTable();
	~CDMinifigComponentTable();
	std::string GetName(void) const override;

std::vector<CDMinifigComponent> Query(std::function<bool(CDMinifigComponent)> predicate);
	std::vector<CDMinifigComponent> GetEntries(void) const;
};
