#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.205280
//DO NOT EDIT THIS FILE MANUALLY!

struct CDMinifigDecals_Torsos {
	int ID;
	std::string High_path;
	bool CharacterCreateValid;
	std::string _description;
	bool male;
	bool female;
};

class CDMinifigDecals_TorsosTable : public CDTable {
private:
	std::vector<CDMinifigDecals_Torsos> m_entries;
public:
	CDMinifigDecals_TorsosTable();
	~CDMinifigDecals_TorsosTable();
	std::string GetName(void) const override;

std::vector<CDMinifigDecals_Torsos> Query(std::function<bool(CDMinifigDecals_Torsos)> predicate);
	std::vector<CDMinifigDecals_Torsos> GetEntries(void) const;
};
