#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.218255
//DO NOT EDIT THIS FILE MANUALLY!

struct CDMissionText {
	int id;
	std::string description;
	std::string offer;
	std::string in_progress;
	std::string ready_to_complete;
	std::string story_icon;
	std::string completion_fail_tip;
	std::string completion_succeed_tip;
	std::string chat_state_1;
	std::string chat_state_2;
	std::string chat_state_3;
	std::string chat_state_4;
	std::string missionIcon;
	std::string offerNPCIcon;
	int IconID;
	std::string accept_chat_bubble;
	std::string offer_repeatable;
	std::string bubble_prereq_not_met;
	std::string chat_state_3_turnin;
	std::string chat_state_4_turnin;
	std::string state_1_anim;
	std::string state_2_anim;
	std::string state_3_anim;
	std::string state_4_anim;
	std::string state_3_turnin_anim;
	std::string state_4_turnin_anim;
	std::string onclick_anim;
	std::string CinematicAccepted;
	float CinematicAcceptedLeadin;
	std::string CinematicCompleted;
	float CinematicCompletedLeadin;
	std::string CinematicRepeatable;
	float CinematicRepeatableLeadin;
	std::string CinematicRepeatableCompleted;
	float CinematicRepeatableCompletedLeadin;
	std::string AudioEventGUID_Interact;
	std::string AudioEventGUID_OfferAccept;
	std::string AudioEventGUID_OfferDeny;
	std::string AudioEventGUID_Completed;
	std::string AudioEventGUID_TurnIn;
	std::string AudioEventGUID_Failed;
	std::string AudioEventGUID_Progress;
};

class CDMissionTextTable : public CDTable {
private:
	std::vector<CDMissionText> m_entries;
public:
	CDMissionTextTable();
	~CDMissionTextTable();
	std::string GetName(void) const override;

std::vector<CDMissionText> Query(std::function<bool(CDMissionText)> predicate);
	std::vector<CDMissionText> GetEntries(void) const;
};
