#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.201289
//DO NOT EDIT THIS FILE MANUALLY!

struct CDMinifigDecals_Mouths {
	int ID;
	std::string High_path;
	std::string Low_path;
	bool CharacterCreateValid;
	bool male;
	bool female;
};

class CDMinifigDecals_MouthsTable : public CDTable {
private:
	std::vector<CDMinifigDecals_Mouths> m_entries;
public:
	CDMinifigDecals_MouthsTable();
	~CDMinifigDecals_MouthsTable();
	std::string GetName(void) const override;

std::vector<CDMinifigDecals_Mouths> Query(std::function<bool(CDMinifigDecals_Mouths)> predicate);
	std::vector<CDMinifigDecals_Mouths> GetEntries(void) const;
};
