#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.196303
//DO NOT EDIT THIS FILE MANUALLY!

struct CDMinifigDecals_Eyes {
	int ID;
	std::string High_path;
	std::string Low_path;
	bool CharacterCreateValid;
	bool male;
	bool female;
};

class CDMinifigDecals_EyesTable : public CDTable {
private:
	std::vector<CDMinifigDecals_Eyes> m_entries;
public:
	CDMinifigDecals_EyesTable();
	~CDMinifigDecals_EyesTable();
	std::string GetName(void) const override;

std::vector<CDMinifigDecals_Eyes> Query(std::function<bool(CDMinifigDecals_Eyes)> predicate);
	std::vector<CDMinifigDecals_Eyes> GetEntries(void) const;
};
