#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.190339
//DO NOT EDIT THIS FILE MANUALLY!

struct CDMinifigDecals_Eyebrows {
	int ID;
	std::string High_path;
	std::string Low_path;
	bool CharacterCreateValid;
	bool male;
	bool female;
};

class CDMinifigDecals_EyebrowsTable : public CDTable {
private:
	std::vector<CDMinifigDecals_Eyebrows> m_entries;
public:
	CDMinifigDecals_EyebrowsTable();
	~CDMinifigDecals_EyebrowsTable();
	std::string GetName(void) const override;

std::vector<CDMinifigDecals_Eyebrows> Query(std::function<bool(CDMinifigDecals_Eyebrows)> predicate);
	std::vector<CDMinifigDecals_Eyebrows> GetEntries(void) const;
};
