#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.228217
//DO NOT EDIT THIS FILE MANUALLY!

struct CDModularBuildComponent {
	int id;
	int buildType;
	std::string xml;
	int createdLOT;
	int createdPhysicsID;
};

class CDModularBuildComponentTable : public CDTable {
private:
	std::vector<CDModularBuildComponent> m_entries;
public:
	CDModularBuildComponentTable();
	~CDModularBuildComponentTable();
	std::string GetName(void) const override;

std::vector<CDModularBuildComponent> Query(std::function<bool(CDModularBuildComponent)> predicate);
	std::vector<CDModularBuildComponent> GetEntries(void) const;
};
