#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.232207
//DO NOT EDIT THIS FILE MANUALLY!

struct CDMotionFX {
	int id;
	int typeID;
	float slamVelocity;
	float addVelocity;
	float duration;
	std::string destGroupName;
	float startScale;
	float endScale;
};

class CDMotionFXTable : public CDTable {
private:
	std::vector<CDMotionFX> m_entries;
public:
	CDMotionFXTable();
	~CDMotionFXTable();
	std::string GetName(void) const override;

std::vector<CDMotionFX> Query(std::function<bool(CDMotionFX)> predicate);
	std::vector<CDMotionFX> GetEntries(void) const;
};
