#include "CDModelBehaviorTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.225231
//DO NOT EDIT THIS FILE MANUALLY!

CDModelBehaviorTable::CDModelBehaviorTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM ModelBehavior");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM ModelBehavior");
	while (!tableData.eof()) {
		CDModelBehavior entry;
		entry.id = tableData.getIntField(0, int{});
		entry.definitionXMLfilename = tableData.getStringField(1, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDModelBehaviorTable::~CDModelBehaviorTable() {
}

std::string CDModelBehaviorTable::GetName(void) const {
	return "ModelBehavior";
}

std::vector<CDModelBehavior> CDModelBehaviorTable::Query(std::function<bool(CDModelBehavior)> predicate) {
	std::vector<CDModelBehavior> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDModelBehavior> CDModelBehaviorTable::GetEntries(void) const {
	return this->m_entries;
}
