#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.236434
//DO NOT EDIT THIS FILE MANUALLY!

struct CDNPCCreateData {
	int npcCreateID;
	std::string NPCtype;
	std::string Subtype;
	std::string SubSubType;
	std::string animationGroupType;
	std::string RenderAsset;
	int ScriptReference;
	int DestructableReference;
	int PhysicsReference;
	int PhysicsTypeRef;
	int VendorReference;
};

class CDNPCCreateDataTable : public CDTable {
private:
	std::vector<CDNPCCreateData> m_entries;
public:
	CDNPCCreateDataTable();
	~CDNPCCreateDataTable();
	std::string GetName(void) const override;

std::vector<CDNPCCreateData> Query(std::function<bool(CDNPCCreateData)> predicate);
	std::vector<CDNPCCreateData> GetEntries(void) const;
};
