#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.242181
//DO NOT EDIT THIS FILE MANUALLY!

struct CDNpcIcons {
	int id;
	int color;
	float offset;
	int LOT;
	bool isClickable;
	float scale;
	bool rotateToFace;
	std::string description;
};

class CDNpcIconsTable : public CDTable {
private:
	std::vector<CDNpcIcons> m_entries;
public:
	CDNpcIconsTable();
	~CDNpcIconsTable();
	std::string GetName(void) const override;

std::vector<CDNpcIcons> Query(std::function<bool(CDNpcIcons)> predicate);
	std::vector<CDNpcIcons> GetEntries(void) const;
};
