#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.250159
//DO NOT EDIT THIS FILE MANUALLY!

struct CDObjectSkills {
	int objectTemplate;
	int skillID;
	int castOnType;
	int AICombatWeight;
};

class CDObjectSkillsTable : public CDTable {
private:
	std::vector<CDObjectSkills> m_entries;
public:
	CDObjectSkillsTable();
	~CDObjectSkillsTable();
	std::string GetName(void) const override;

std::vector<CDObjectSkills> Query(std::function<bool(CDObjectSkills)> predicate);
	std::vector<CDObjectSkills> GetEntries(void) const;
};
