#include "CDObjectSkillsTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.252158
//DO NOT EDIT THIS FILE MANUALLY!

CDObjectSkillsTable::CDObjectSkillsTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM ObjectSkills");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM ObjectSkills");
	while (!tableData.eof()) {
		CDObjectSkills entry;
		entry.objectTemplate = tableData.getIntField(0, int{});
		entry.skillID = tableData.getIntField(1, int{});
		entry.castOnType = tableData.getIntField(2, int{});
		entry.AICombatWeight = tableData.getIntField(3, int{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDObjectSkillsTable::~CDObjectSkillsTable() {
}

std::string CDObjectSkillsTable::GetName(void) const {
	return "ObjectSkills";
}

std::vector<CDObjectSkills> CDObjectSkillsTable::Query(std::function<bool(CDObjectSkills)> predicate) {
	std::vector<CDObjectSkills> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDObjectSkills> CDObjectSkillsTable::GetEntries(void) const {
	return this->m_entries;
}
