#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.246169
//DO NOT EDIT THIS FILE MANUALLY!

struct CDObjects {
	int id;
	std::string name;
	bool placeable;
	std::string type;
	std::string description;
	bool localize;
	int npcTemplateID;
	std::string displayName;
	float interactionDistance;
	bool nametag;
};

class CDObjectsTable : public CDTable {
private:
	std::vector<CDObjects> m_entries;
public:
	CDObjectsTable();
	~CDObjectsTable();
	std::string GetName(void) const override;

std::vector<CDObjects> Query(std::function<bool(CDObjects)> predicate);
	std::vector<CDObjects> GetEntries(void) const;
};
