#include "CDPackageComponentTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.257140
//DO NOT EDIT THIS FILE MANUALLY!

CDPackageComponentTable::CDPackageComponentTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM PackageComponent");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM PackageComponent");
	while (!tableData.eof()) {
		CDPackageComponent entry;
		entry.id = tableData.getIntField(0, int{});
		entry.LootMatrixIndex = tableData.getIntField(1, int{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDPackageComponentTable::~CDPackageComponentTable() {
}

std::string CDPackageComponentTable::GetName(void) const {
	return "PackageComponent";
}

std::vector<CDPackageComponent> CDPackageComponentTable::Query(std::function<bool(CDPackageComponent)> predicate) {
	std::vector<CDPackageComponent> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDPackageComponent> CDPackageComponentTable::GetEntries(void) const {
	return this->m_entries;
}
