#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.256377
//DO NOT EDIT THIS FILE MANUALLY!

struct CDPackageComponent {
	int id;
	int LootMatrixIndex;
};

class CDPackageComponentTable : public CDTable {
private:
	std::vector<CDPackageComponent> m_entries;
public:
	CDPackageComponentTable();
	~CDPackageComponentTable();
	std::string GetName(void) const override;

std::vector<CDPackageComponent> Query(std::function<bool(CDPackageComponent)> predicate);
	std::vector<CDPackageComponent> GetEntries(void) const;
};
