#include "CDPetNestComponentTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.271103
//DO NOT EDIT THIS FILE MANUALLY!

CDPetNestComponentTable::CDPetNestComponentTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM PetNestComponent");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM PetNestComponent");
	while (!tableData.eof()) {
		CDPetNestComponent entry;
		entry.id = tableData.getIntField(0, int{});
		entry.ElementalType = tableData.getIntField(1, int{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDPetNestComponentTable::~CDPetNestComponentTable() {
}

std::string CDPetNestComponentTable::GetName(void) const {
	return "PetNestComponent";
}

std::vector<CDPetNestComponent> CDPetNestComponentTable::Query(std::function<bool(CDPetNestComponent)> predicate) {
	std::vector<CDPetNestComponent> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDPetNestComponent> CDPetNestComponentTable::GetEntries(void) const {
	return this->m_entries;
}
