#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.261132
//DO NOT EDIT THIS FILE MANUALLY!

struct CDPetAbilities {
	int id;
	std::string AbilityName;
	int ImaginationCost;
	std::string DisplayName;
};

class CDPetAbilitiesTable : public CDTable {
private:
	std::vector<CDPetAbilities> m_entries;
public:
	CDPetAbilitiesTable();
	~CDPetAbilitiesTable();
	std::string GetName(void) const override;

std::vector<CDPetAbilities> Query(std::function<bool(CDPetAbilities)> predicate);
	std::vector<CDPetAbilities> GetEntries(void) const;
};
