#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.269108
//DO NOT EDIT THIS FILE MANUALLY!

struct CDPetNestComponent {
	int id;
	int ElementalType;
};

class CDPetNestComponentTable : public CDTable {
private:
	std::vector<CDPetNestComponent> m_entries;
public:
	CDPetNestComponentTable();
	~CDPetNestComponentTable();
	std::string GetName(void) const override;

std::vector<CDPetNestComponent> Query(std::function<bool(CDPetNestComponent)> predicate);
	std::vector<CDPetNestComponent> GetEntries(void) const;
};
