#include "CDPetAbilitiesTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.262473
//DO NOT EDIT THIS FILE MANUALLY!

CDPetAbilitiesTable::CDPetAbilitiesTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM PetAbilities");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM PetAbilities");
	while (!tableData.eof()) {
		CDPetAbilities entry;
		entry.id = tableData.getIntField(0, int{});
		entry.AbilityName = tableData.getStringField(1, std::string{}.c_str());
		entry.ImaginationCost = tableData.getIntField(2, int{});
		entry.DisplayName = tableData.getStringField(3, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDPetAbilitiesTable::~CDPetAbilitiesTable() {
}

std::string CDPetAbilitiesTable::GetName(void) const {
	return "PetAbilities";
}

std::vector<CDPetAbilities> CDPetAbilitiesTable::Query(std::function<bool(CDPetAbilities)> predicate) {
	std::vector<CDPetAbilities> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDPetAbilities> CDPetAbilitiesTable::GetEntries(void) const {
	return this->m_entries;
}
