#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.265119
//DO NOT EDIT THIS FILE MANUALLY!

struct CDPetComponent {
	int id;
	std::string description;
	float minTameUpdateTime;
	float maxTameUpdateTime;
	float percentTameChance;
	float tamability;
	int elementType;
	float walkSpeed;
	float runSpeed;
	float sprintSpeed;
	float idleTimeMin;
	float idleTimeMax;
	int eggLotId;
	int petForm;
	float imaginationDrainRate;
	std::string AudioMetaEventSet;
	int playerFlag;
};

class CDPetComponentTable : public CDTable {
private:
	std::vector<CDPetComponent> m_entries;
public:
	CDPetComponentTable();
	~CDPetComponentTable();
	std::string GetName(void) const override;

std::vector<CDPetComponent> Query(std::function<bool(CDPetComponent)> predicate);
	std::vector<CDPetComponent> GetEntries(void) const;
};
