#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.274095
//DO NOT EDIT THIS FILE MANUALLY!

struct CDPhysicsComponent {
	int id;
	float isStatic;
	std::string physics_asset;
	float jump;
	float doublejump;
	float speed;
	float rotSpeed;
	float playerHeight;
	float playerRadius;
	int pcShapeType;
	int collisionGroup;
	float airSpeed;
	std::string boundaryAsset;
	float jumpAirSpeed;
	float friction;
};

class CDPhysicsComponentTable : public CDTable {
private:
	std::vector<CDPhysicsComponent> m_entries;
	std::map<int, CDPhysicsComponent> m_mappedEntities;

public:
	CDPhysicsComponentTable();
	~CDPhysicsComponentTable();
	std::string GetName(void) const override;

	std::vector<CDPhysicsComponent> Query(std::function<bool(CDPhysicsComponent)> predicate);
	std::vector<CDPhysicsComponent> GetEntries(void) const;

	CDPhysicsComponent* GetByID(unsigned int ID);
};
