#include "CDPlayerFlagsTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.281077
//DO NOT EDIT THIS FILE MANUALLY!

CDPlayerFlagsTable::CDPlayerFlagsTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM PlayerFlags");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM PlayerFlags");
	while (!tableData.eof()) {
		CDPlayerFlags entry;
		entry.id = tableData.getIntField(0, int{});
		entry.description = tableData.getStringField(1, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDPlayerFlagsTable::~CDPlayerFlagsTable() {
}

std::string CDPlayerFlagsTable::GetName(void) const {
	return "PlayerFlags";
}

std::vector<CDPlayerFlags> CDPlayerFlagsTable::Query(std::function<bool(CDPlayerFlags)> predicate) {
	std::vector<CDPlayerFlags> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDPlayerFlags> CDPlayerFlagsTable::GetEntries(void) const {
	return this->m_entries;
}
