#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.279087
//DO NOT EDIT THIS FILE MANUALLY!

struct CDPlayerFlags {
	int id;
	std::string description;
};

class CDPlayerFlagsTable : public CDTable {
private:
	std::vector<CDPlayerFlags> m_entries;
public:
	CDPlayerFlagsTable();
	~CDPlayerFlagsTable();
	std::string GetName(void) const override;

std::vector<CDPlayerFlags> Query(std::function<bool(CDPlayerFlags)> predicate);
	std::vector<CDPlayerFlags> GetEntries(void) const;
};
