#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.285066
//DO NOT EDIT THIS FILE MANUALLY!

struct CDPreconditions {
	int id;
	int type;
	std::string description;
	std::string targetLOT;
	std::string targetGroup;
	int targetCount;
	std::string FailureReason;
};

class CDPreconditionsTable : public CDTable {
private:
	std::vector<CDPreconditions> m_entries;
public:
	CDPreconditionsTable();
	~CDPreconditionsTable();
	std::string GetName(void) const override;

std::vector<CDPreconditions> Query(std::function<bool(CDPreconditions)> predicate);
	std::vector<CDPreconditions> GetEntries(void) const;
};
