#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.288057
//DO NOT EDIT THIS FILE MANUALLY!

struct CDPreconditionTypes {
	int id;
	std::string description;
};

class CDPreconditionTypesTable : public CDTable {
private:
	std::vector<CDPreconditionTypes> m_entries;
public:
	CDPreconditionTypesTable();
	~CDPreconditionTypesTable();
	std::string GetName(void) const override;

std::vector<CDPreconditionTypes> Query(std::function<bool(CDPreconditionTypes)> predicate);
	std::vector<CDPreconditionTypes> GetEntries(void) const;
};
