#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.292047
//DO NOT EDIT THIS FILE MANUALLY!

struct CDPropertyTemplate {
	uint64_t id;
	uint64_t mapID;
	uint64_t vendorMapID;
	std::string spawnName;
	int type;
	int sizecode;
	uint64_t minimumPrice;
	uint64_t rentDuration;
	std::string path;
	std::string name;
	std::string description;
	int cloneLimit;
	float reputationPerVote;
	int durationType;
	int achievementRequired;
	float zoneX;
	float zoneY;
	float zoneZ;
	float maxBuildHeight;
};

class CDPropertyTemplateTable : public CDTable {
private:
	std::vector<CDPropertyTemplate> m_entries;
public:
	CDPropertyTemplateTable();
	~CDPropertyTemplateTable();
	std::string GetName(void) const override;

std::vector<CDPropertyTemplate> Query(std::function<bool(CDPropertyTemplate)> predicate);
	std::vector<CDPropertyTemplate> GetEntries(void) const;
};
