#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.342916
//DO NOT EDIT THIS FILE MANUALLY!

struct CDRarityTableIndex {
	int RarityTableIndex;
	std::string description;
};

class CDRarityTableIndexTable : public CDTable {
private:
	std::vector<CDRarityTableIndex> m_entries;
public:
	CDRarityTableIndexTable();
	~CDRarityTableIndexTable();
	std::string GetName(void) const override;

std::vector<CDRarityTableIndex> Query(std::function<bool(CDRarityTableIndex)> predicate);
	std::vector<CDRarityTableIndex> GetEntries(void) const;
};
