#include "CDRarityTableIndexTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.344911
//DO NOT EDIT THIS FILE MANUALLY!

CDRarityTableIndexTable::CDRarityTableIndexTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM RarityTableIndex");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM RarityTableIndex");
	while (!tableData.eof()) {
		CDRarityTableIndex entry;
		entry.RarityTableIndex = tableData.getIntField(0, int{});
		entry.description = tableData.getStringField(1, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDRarityTableIndexTable::~CDRarityTableIndexTable() {
}

std::string CDRarityTableIndexTable::GetName(void) const {
	return "RarityTableIndex";
}

std::vector<CDRarityTableIndex> CDRarityTableIndexTable::Query(std::function<bool(CDRarityTableIndex)> predicate) {
	std::vector<CDRarityTableIndex> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDRarityTableIndex> CDRarityTableIndexTable::GetEntries(void) const {
	return this->m_entries;
}
