#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.337924
//DO NOT EDIT THIS FILE MANUALLY!

struct CDRarityTable {
	int id;
	float randmax;
	int rarity;
	int RarityTableIndex;
};

class CDRarityTableTable : public CDTable {
private:
	std::vector<CDRarityTable> m_entries;
public:
	CDRarityTableTable();
	~CDRarityTableTable();
	std::string GetName(void) const override;

std::vector<CDRarityTable> Query(std::function<bool(CDRarityTable)> predicate);
	std::vector<CDRarityTable> GetEntries(void) const;
};
