#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.323961
//DO NOT EDIT THIS FILE MANUALLY!

struct CDRacingModuleComponent {
	int id;
	float topSpeed;
	float acceleration;
	float handling;
	float stability;
	float imagination;
};

class CDRacingModuleComponentTable : public CDTable {
private:
	std::vector<CDRacingModuleComponent> m_entries;
public:
	CDRacingModuleComponentTable();
	~CDRacingModuleComponentTable();
	std::string GetName(void) const override;

std::vector<CDRacingModuleComponent> Query(std::function<bool(CDRacingModuleComponent)> predicate);
	std::vector<CDRacingModuleComponent> GetEntries(void) const;
};
