#include "CDRarityTableTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.338921
//DO NOT EDIT THIS FILE MANUALLY!

CDRarityTableTable::CDRarityTableTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM RarityTable");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM RarityTable");
	while (!tableData.eof()) {
		CDRarityTable entry;
		entry.id = tableData.getIntField(0, int{});
		entry.randmax = tableData.getFloatField(1, float{});
		entry.rarity = tableData.getIntField(2, int{});
		entry.RarityTableIndex = tableData.getIntField(3, int{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDRarityTableTable::~CDRarityTableTable() {
}

std::string CDRarityTableTable::GetName(void) const {
	return "RarityTable";
}

std::vector<CDRarityTable> CDRarityTableTable::Query(std::function<bool(CDRarityTable)> predicate) {
	std::vector<CDRarityTable> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDRarityTable> CDRarityTableTable::GetEntries(void) const {
	return this->m_entries;
}
