#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.373829
//DO NOT EDIT THIS FILE MANUALLY!

struct CDRenderComponentFlash {
	int id;
	bool interactive;
	bool animated;
	std::string nodeName;
	std::string flashPath;
	std::string elementName;
	int _uid;
};

class CDRenderComponentFlashTable : public CDTable {
private:
	std::vector<CDRenderComponentFlash> m_entries;
public:
	CDRenderComponentFlashTable();
	~CDRenderComponentFlashTable();
	std::string GetName(void) const override;

std::vector<CDRenderComponentFlash> Query(std::function<bool(CDRenderComponentFlash)> predicate);
	std::vector<CDRenderComponentFlash> GetEntries(void) const;
};
