#include "CDRenderIconAssetsTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.383802
//DO NOT EDIT THIS FILE MANUALLY!

CDRenderIconAssetsTable::CDRenderIconAssetsTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM RenderIconAssets");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM RenderIconAssets");
	while (!tableData.eof()) {
		CDRenderIconAssets entry;
		entry.id = tableData.getIntField(0, int{});
		entry.icon_asset = tableData.getStringField(1, std::string{}.c_str());
		entry.blank_column = tableData.getStringField(2, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDRenderIconAssetsTable::~CDRenderIconAssetsTable() {
}

std::string CDRenderIconAssetsTable::GetName(void) const {
	return "RenderIconAssets";
}

std::vector<CDRenderIconAssets> CDRenderIconAssetsTable::Query(std::function<bool(CDRenderIconAssets)> predicate) {
	std::vector<CDRenderIconAssets> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDRenderIconAssets> CDRenderIconAssetsTable::GetEntries(void) const {
	return this->m_entries;
}
