#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.354878
//DO NOT EDIT THIS FILE MANUALLY!

struct CDRebuildComponent {
	int id;
	float reset_time;
	float complete_time;
	int take_imagination;
	bool interruptible;
	bool self_activator;
	std::string custom_modules;
	int prerequisite_imagination;
	int activityID;
};

class CDRebuildComponentTable : public CDTable {
private:
	std::vector<CDRebuildComponent> m_entries;
public:
	CDRebuildComponentTable();
	~CDRebuildComponentTable();
	std::string GetName(void) const override;

std::vector<CDRebuildComponent> Query(std::function<bool(CDRebuildComponent)> predicate);
	std::vector<CDRebuildComponent> GetEntries(void) const;
};
