#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.385796
//DO NOT EDIT THIS FILE MANUALLY!

struct CDReputationRewards {
	int repLevel;
	int sublevel;
	float reputation;
};

class CDReputationRewardsTable : public CDTable {
private:
	std::vector<CDReputationRewards> m_entries;
public:
	CDReputationRewardsTable();
	~CDReputationRewardsTable();
	std::string GetName(void) const override;

std::vector<CDReputationRewards> Query(std::function<bool(CDReputationRewards)> predicate);
	std::vector<CDReputationRewards> GetEntries(void) const;
};
