#include "CDReputationRewardsTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.387791
//DO NOT EDIT THIS FILE MANUALLY!

CDReputationRewardsTable::CDReputationRewardsTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM ReputationRewards");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM ReputationRewards");
	while (!tableData.eof()) {
		CDReputationRewards entry;
		entry.repLevel = tableData.getIntField(0, int{});
		entry.sublevel = tableData.getIntField(1, int{});
		entry.reputation = tableData.getFloatField(2, float{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDReputationRewardsTable::~CDReputationRewardsTable() {
}

std::string CDReputationRewardsTable::GetName(void) const {
	return "ReputationRewards";
}

std::vector<CDReputationRewards> CDReputationRewardsTable::Query(std::function<bool(CDReputationRewards)> predicate) {
	std::vector<CDReputationRewards> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDReputationRewards> CDReputationRewardsTable::GetEntries(void) const {
	return this->m_entries;
}
