#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.363858
//DO NOT EDIT THIS FILE MANUALLY!

struct CDRebuildSections {
	int id;
	int rebuildID;
	int objectID;
	float offset_x;
	float offset_y;
	float offset_z;
	float fall_angle_x;
	float fall_angle_y;
	float fall_angle_z;
	float fall_height;
	std::string requires_list;
	int size;
	bool bPlaced;
};

class CDRebuildSectionsTable : public CDTable {
private:
	std::vector<CDRebuildSections> m_entries;
public:
	CDRebuildSectionsTable();
	~CDRebuildSectionsTable();
	std::string GetName(void) const override;

std::vector<CDRebuildSections> Query(std::function<bool(CDRebuildSections)> predicate);
	std::vector<CDRebuildSections> GetEntries(void) const;
};
