#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.390783
//DO NOT EDIT THIS FILE MANUALLY!

struct CDSceneTable {
	int sceneID;
	std::string sceneName;
};

class CDSceneTableTable : public CDTable {
private:
	std::vector<CDSceneTable> m_entries;
public:
	CDSceneTableTable();
	~CDSceneTableTable();
	std::string GetName(void) const override;

std::vector<CDSceneTable> Query(std::function<bool(CDSceneTable)> predicate);
	std::vector<CDSceneTable> GetEntries(void) const;
};
