#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.403749
//DO NOT EDIT THIS FILE MANUALLY!

struct CDScriptComponent {
	int id;
	std::string script_name;
	std::string client_script_name;
};

class CDScriptComponentTable : public CDTable {
private:
	std::vector<CDScriptComponent> m_entries;
public:
	CDScriptComponentTable();
	~CDScriptComponentTable();
	std::string GetName(void) const override;

std::vector<CDScriptComponent> Query(std::function<bool(CDScriptComponent)> predicate);
	std::vector<CDScriptComponent> GetEntries(void) const;
};
