#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.406740
//DO NOT EDIT THIS FILE MANUALLY!

struct CDSkillBehavior {
	int skillID;
	int behaviorID;
	std::string name;
	std::string description;
	int imaginationcost;
	int cooldowngroup;
	float cooldown;
	bool inNpcEditor;
	int skillIcon;
	std::string oomSkillID;
	int oomBehaviorEffectID;
	int castTypeDesc;
	int imBonusUI;
	int lifeBonusUI;
	int armorBonusUI;
	int imHealUI;
	int lifeHealUI;
	int armorHealUI;
	int damageUI;
	std::string descriptionUI;
};

class CDSkillBehaviorTable : public CDTable {
private:
	std::vector<CDSkillBehavior> m_entries;
public:
	CDSkillBehaviorTable();
	~CDSkillBehaviorTable();
	std::string GetName(void) const override;

std::vector<CDSkillBehavior> Query(std::function<bool(CDSkillBehavior)> predicate);
	std::vector<CDSkillBehavior> GetEntries(void) const;
};
