#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.423695
//DO NOT EDIT THIS FILE MANUALLY!

struct CDSmashableComponent {
	int id;
	int LootMatrixIndex;
};

class CDSmashableComponentTable : public CDTable {
private:
	std::vector<CDSmashableComponent> m_entries;
public:
	CDSmashableComponentTable();
	~CDSmashableComponentTable();
	std::string GetName(void) const override;

std::vector<CDSmashableComponent> Query(std::function<bool(CDSmashableComponent)> predicate);
	std::vector<CDSmashableComponent> GetEntries(void) const;
};
