#include "CDSmashableElementsTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.431674
//DO NOT EDIT THIS FILE MANUALLY!

CDSmashableElementsTable::CDSmashableElementsTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM SmashableElements");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM SmashableElements");
	while (!tableData.eof()) {
		CDSmashableElements entry;
		entry.elementID = tableData.getIntField(0, int{});
		entry.dropWeight = tableData.getIntField(1, int{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDSmashableElementsTable::~CDSmashableElementsTable() {
}

std::string CDSmashableElementsTable::GetName(void) const {
	return "SmashableElements";
}

std::vector<CDSmashableElements> CDSmashableElementsTable::Query(std::function<bool(CDSmashableElements)> predicate) {
	std::vector<CDSmashableElements> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDSmashableElements> CDSmashableElementsTable::GetEntries(void) const {
	return this->m_entries;
}
