#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.429679
//DO NOT EDIT THIS FILE MANUALLY!

struct CDSmashableElements {
	int elementID;
	int dropWeight;
};

class CDSmashableElementsTable : public CDTable {
private:
	std::vector<CDSmashableElements> m_entries;
public:
	CDSmashableElementsTable();
	~CDSmashableElementsTable();
	std::string GetName(void) const override;

std::vector<CDSmashableElements> Query(std::function<bool(CDSmashableElements)> predicate);
	std::vector<CDSmashableElements> GetEntries(void) const;
};
