#include "CDSpeedchatMenuTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.433668
//DO NOT EDIT THIS FILE MANUALLY!

CDSpeedchatMenuTable::CDSpeedchatMenuTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM SpeedchatMenu");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM SpeedchatMenu");
	while (!tableData.eof()) {
		CDSpeedchatMenu entry;
		entry.id = tableData.getIntField(0, int{});
		entry.parentId = tableData.getIntField(1, int{});
		entry.emoteId = tableData.getIntField(2, int{});
		entry.menuText = tableData.getStringField(3, std::string{}.c_str());
		entry.imageName = tableData.getStringField(4, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDSpeedchatMenuTable::~CDSpeedchatMenuTable() {
}

std::string CDSpeedchatMenuTable::GetName(void) const {
	return "SpeedchatMenu";
}

std::vector<CDSpeedchatMenu> CDSpeedchatMenuTable::Query(std::function<bool(CDSpeedchatMenu)> predicate) {
	std::vector<CDSpeedchatMenu> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDSpeedchatMenu> CDSpeedchatMenuTable::GetEntries(void) const {
	return this->m_entries;
}
