#include "CDSurfaceTypeTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.437657
//DO NOT EDIT THIS FILE MANUALLY!

CDSurfaceTypeTable::CDSurfaceTypeTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM SurfaceType");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM SurfaceType");
	while (!tableData.eof()) {
		CDSurfaceType entry;
		entry.SurfaceType = tableData.getIntField(0, int{});
		entry.Name = tableData.getStringField(1, std::string{}.c_str());
		entry.FootstepNDAudioMetaEventSetName = tableData.getStringField(2, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDSurfaceTypeTable::~CDSurfaceTypeTable() {
}

std::string CDSurfaceTypeTable::GetName(void) const {
	return "SurfaceType";
}

std::vector<CDSurfaceType> CDSurfaceTypeTable::Query(std::function<bool(CDSurfaceType)> predicate) {
	std::vector<CDSurfaceType> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDSurfaceType> CDSurfaceTypeTable::GetEntries(void) const {
	return this->m_entries;
}
