#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.439652
//DO NOT EDIT THIS FILE MANUALLY!

struct CDsysdiagrams {
	std::string name;
	int principal_id;
	int diagram_id;
	int version;
	//varbinary definition;
};

class CDsysdiagramsTable : public CDTable {
private:
	std::vector<CDsysdiagrams> m_entries;
public:
	CDsysdiagramsTable();
	~CDsysdiagramsTable();
	std::string GetName(void) const override;

std::vector<CDsysdiagrams> Query(std::function<bool(CDsysdiagrams)> predicate);
	std::vector<CDsysdiagrams> GetEntries(void) const;
};
