#include "CDsysdiagramsTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.440655
//DO NOT EDIT THIS FILE MANUALLY!

CDsysdiagramsTable::CDsysdiagramsTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM sysdiagrams");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM sysdiagrams");
	while (!tableData.eof()) {
		CDsysdiagrams entry;
		entry.name = tableData.getStringField(0, std::string{}.c_str());
		entry.principal_id = tableData.getIntField(1, int{});
		entry.diagram_id = tableData.getIntField(2, int{});
		entry.version = tableData.getIntField(3, int{});
		//entry.definition = tableData.getvarbinaryField(4, varbinary{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDsysdiagramsTable::~CDsysdiagramsTable() {
}

std::string CDsysdiagramsTable::GetName(void) const {
	return "sysdiagrams";
}

std::vector<CDsysdiagrams> CDsysdiagramsTable::Query(std::function<bool(CDsysdiagrams)> predicate) {
	std::vector<CDsysdiagrams> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDsysdiagrams> CDsysdiagramsTable::GetEntries(void) const {
	return this->m_entries;
}
