#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.444639
//DO NOT EDIT THIS FILE MANUALLY!

struct CDTamingBuildPuzzles {
	int id;
	int PuzzleModelLot;
	int NPCLot;
	std::string ValidPiecesLXF;
	std::string InvalidPiecesLXF;
	int Difficulty;
	int Timelimit;
	int NumValidPieces;
	int TotalNumPieces;
	std::string ModelName;
	std::string FullModelLXF;
	float Duration;
	int imagCostPerBuild;
};

class CDTamingBuildPuzzlesTable : public CDTable {
private:
	std::vector<CDTamingBuildPuzzles> m_entries;
public:
	CDTamingBuildPuzzlesTable();
	~CDTamingBuildPuzzlesTable();
	std::string GetName(void) const override;

std::vector<CDTamingBuildPuzzles> Query(std::function<bool(CDTamingBuildPuzzles)> predicate);
	std::vector<CDTamingBuildPuzzles> GetEntries(void) const;
};
