#include "CDTextDescriptionTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.455609
//DO NOT EDIT THIS FILE MANUALLY!

CDTextDescriptionTable::CDTextDescriptionTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM TextDescription");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM TextDescription");
	while (!tableData.eof()) {
		CDTextDescription entry;
		entry.TextID = tableData.getIntField(0, int{});
		entry.TestDescription = tableData.getStringField(1, std::string{}.c_str());
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDTextDescriptionTable::~CDTextDescriptionTable() {
}

std::string CDTextDescriptionTable::GetName(void) const {
	return "TextDescription";
}

std::vector<CDTextDescription> CDTextDescriptionTable::Query(std::function<bool(CDTextDescription)> predicate) {
	std::vector<CDTextDescription> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDTextDescription> CDTextDescriptionTable::GetEntries(void) const {
	return this->m_entries;
}
