#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.451621
//DO NOT EDIT THIS FILE MANUALLY!

struct CDtesttable2 {
	int id;
	float realVal;
	std::string varCharVal;
	int intVal;
	uint64_t int64val;
	bool bitVal;
	int smallVal;
	int tinyVal;
	float doubleVal;
	//varbinary binaryVal;
	std::string timeVal;
	std::string charVal;
	std::string name;
	std::string nameLONG;
	std::string nameShort;
};

class CDtesttable2Table : public CDTable {
private:
	std::vector<CDtesttable2> m_entries;
public:
	CDtesttable2Table();
	~CDtesttable2Table();
	std::string GetName(void) const override;

std::vector<CDtesttable2> Query(std::function<bool(CDtesttable2)> predicate);
	std::vector<CDtesttable2> GetEntries(void) const;
};
