#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.456607
//DO NOT EDIT THIS FILE MANUALLY!

struct CDTextLanguage {
	int TextID;
	int LanguageID;
	std::string Text;
};

class CDTextLanguageTable : public CDTable {
private:
	std::vector<CDTextLanguage> m_entries;
public:
	CDTextLanguageTable();
	~CDTextLanguageTable();
	std::string GetName(void) const override;

std::vector<CDTextLanguage> Query(std::function<bool(CDTextLanguage)> predicate);
	std::vector<CDTextLanguage> GetEntries(void) const;
};
