#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.462594
//DO NOT EDIT THIS FILE MANUALLY!

struct CDTrailEffects {
	int trailID;
	std::string description;
	std::string textureName;
	int blendmode;
	float cardlifetime;
	float colorlifetime;
	float minTailFade;
	float tailFade;
	int max_particles;
	float birthDelay;
	float deathDelay;
	std::string bone1;
	std::string bone2;
	float texLength;
	float texWidth;
	float startColorR;
	float startColorG;
	float startColorB;
	float startColorA;
	float middleColorR;
	float middleColorG;
	float middleColorB;
	float middleColorA;
	float endColorR;
	float endColorG;
	float endColorB;
	float endColorA;
};

class CDTrailEffectsTable : public CDTable {
private:
	std::vector<CDTrailEffects> m_entries;
public:
	CDTrailEffectsTable();
	~CDTrailEffectsTable();
	std::string GetName(void) const override;

std::vector<CDTrailEffects> Query(std::function<bool(CDTrailEffects)> predicate);
	std::vector<CDTrailEffects> GetEntries(void) const;
};
