#include "CDVendorComponentTable.h"
//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.492515
//DO NOT EDIT THIS FILE MANUALLY!

CDVendorComponentTable::CDVendorComponentTable() {
	unsigned int size = 0;
	auto tableSize = CDClientDatabase::ExecuteQuery("SELECT COUNT(*) FROM VendorComponent");
		while (!tableSize.eof()) {
		size = tableSize.getIntField(0, 0);
		tableSize.nextRow();
	}

	tableSize.finalize();
	this->m_entries.reserve(size);

	auto tableData = CDClientDatabase::ExecuteQuery("SELECT * FROM VendorComponent");
	while (!tableData.eof()) {
		CDVendorComponent entry;
		entry.id = tableData.getIntField(0, int{});
		entry.buyScalar = tableData.getFloatField(1, float{});
		entry.sellScalar = tableData.getFloatField(2, float{});
		entry.refreshTimeSeconds = tableData.getFloatField(3, float{});
		entry.LootMatrixIndex = tableData.getIntField(4, int{});
		this->m_entries.push_back(entry);
		tableData.nextRow();
	}

	tableData.finalize();
}

CDVendorComponentTable::~CDVendorComponentTable() {
}

std::string CDVendorComponentTable::GetName(void) const {
	return "VendorComponent";
}

std::vector<CDVendorComponent> CDVendorComponentTable::Query(std::function<bool(CDVendorComponent)> predicate) {
	std::vector<CDVendorComponent> data = cpplinq::from(this->m_entries)
		>> cpplinq::where(predicate)
		>> cpplinq::to_vector();

	return data;
}

std::vector<CDVendorComponent> CDVendorComponentTable::GetEntries(void) const {
	return this->m_entries;
}
