#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.482537
//DO NOT EDIT THIS FILE MANUALLY!

struct CDVehicleStatMap {
	int id;
	std::string ModuleStat;
	std::string HavokStat;
	float HavokChangePerModuleStat;
};

class CDVehicleStatMapTable : public CDTable {
private:
	std::vector<CDVehicleStatMap> m_entries;
public:
	CDVehicleStatMapTable();
	~CDVehicleStatMapTable();
	std::string GetName(void) const override;

std::vector<CDVehicleStatMap> Query(std::function<bool(CDVehicleStatMap)> predicate);
	std::vector<CDVehicleStatMap> GetEntries(void) const;
};
