#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.490518
//DO NOT EDIT THIS FILE MANUALLY!

struct CDVendorComponent {
	int id;
	float buyScalar;
	float sellScalar;
	float refreshTimeSeconds;
	int LootMatrixIndex;
};

class CDVendorComponentTable : public CDTable {
private:
	std::vector<CDVendorComponent> m_entries;
public:
	CDVendorComponentTable();
	~CDVendorComponentTable();
	std::string GetName(void) const override;

std::vector<CDVendorComponent> Query(std::function<bool(CDVendorComponent)> predicate);
	std::vector<CDVendorComponent> GetEntries(void) const;
};
