#pragma once
#include "CDTable.h"

//Generated by xmlDb2dDatabaseGenerator on 2022-03-04 00:23:33.507471
//DO NOT EDIT THIS FILE MANUALLY!

struct CDZoneTable {
	int zoneID;
	std::string zoneName;
	int scriptID;
	float ghostdistance;
	int population_soft_cap;
	int population_hard_cap;
	std::string DisplayDescription;
	std::string mapFolder;
	float smashableMinDistance;
	float smashableMaxDistance;
	std::string mixerProgram;
	std::string clientPhysicsFramerate;
	std::string serverPhysicsFramerate;
	int zoneControlTemplate;
};

class CDZoneTableTable : public CDTable {
private:
	std::map<unsigned int, CDZoneTable> m_Entries;

public:
	CDZoneTableTable();
	~CDZoneTableTable();
	std::string GetName(void) const override;

	const CDZoneTable* Query(unsigned int zoneID);
};
